[physical_settings]
temperature = 1
L = 10
dimension = 2
J = 1
potts_q = 3
H = 1.0
vec_H = [0.0,1.0,2.0]


[simulation_settings]
time_steps = 10000
recording_steps = 1000

record_magnetisation = true
record_energy = true
record_susceptibility = false
record_specific_heat = false
record_correlation_length = false
record_correlation_function = false
